# Generated by Django 3.2.9 on 2021-11-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('En curso', 'In Progress'), ('Completado', 'Done'), ('Abandonado', 'Abandoned')], default='En curso', max_length=50),
        ),
    ]
