# Generated by Django 3.2.9 on 2021-11-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('En curso', 'En curso'), ('Completado', 'Completado'), ('Abandonado', 'Abandonado')], default='En curso', max_length=50),
        ),
    ]
